const logger = require('../config/logger.config');
const Account = require('../models/account.model');
const Teacher = require('../models/teacher.model');
const Admin = require('../models/admin.model');
const Staff = require('../models/staff.model');
const Student = require('../models/student.model');
const Recruitment = require('../models/recruitment.model');
const Apply = require('../models/apply.model');
const SourceCollect = require('../models/source_collect.model');
const Collect = require('../models/collect.model');
const Spend = require('../models/spend.model');
const CustomerSales = require('../models/customer_sales.model');
const Tutoring = require('../models/tutoring.model');
const Course = require('../models/course.model');
const Classroom = require('../models/classroom.model');
const CalendarDetail = require('../models/calendar_detail.model');
const ClassEvaluate = require('../models/class_evaluate.model');
const TeacherTime = require('../models/teacher_time.model');
const StudentTest = require('../models/student_test.model');
const AttendanceClassOnline = require('../models/attendance_class_online.model');
const StudentList = require('../models/student_list.model');
const StudentAttendance = require('../models/student_attendance.model');
const TestType = require('../models/test_type.model');
const Test = require('../models/test.model');
const File = require('../models/file.model');
const Tuition = require('../models/tuition.model');
const Template = require('../models/template.model');
const TeacherList = require('../models/teacher_list.model');
const ApplicationLeave = require('../models/application_leave.model');
const FileProfile = require('../models/file_profile.model');
const Department = require('../models/department.model');
const SourceApply = require('../models/source_apply.models');
const Supplier = require('../models/supplier.model');
const CustomerNote = require('../models/customer_note.model');
const StudentChangeHour = require('../models/student_change_hour.model');
const StudentEvaluate = require('../models/student_evaluate.model');
const Notification = require('../models/notification.model');
const CourseArise = require('../models/course_arise.model');
const PrintReceipt = require('../models/print_receipt.model');
const StudentListHistory = require('../models/student_list_history.model');
const CriteriaTest = require('../models/criteria_test.model');
const SourceSpend = require('../models/source_spend.model');
const Practice = require('../models/practice.model');
const PracticeStudent = require('../models/practice_student.model');
const ProgressStudentClass = require('../models/progress.model');
const PracticeAdults = require('../models/practice_adults.model');
const PracticeTopicAdults = require('../models/practice_topic_adults.model');
const PracticeTopicDetailAdults = require('../models/practice_topic_detail_adults.model');
const Event = require('../models/event.model');
const EventStudent = require('../models/event_student.model');
const TemplateHistory = require('../models/template_history.model');
const EventSummerClass = require('../models/event_summer_class.model');
const ClassTestCalendar = require('../models/class_test_calendar.model');
const ContributeEvent = require('../models/contribute_event.model');
const StudentOffSummer = require('../models/student_off_summer.model');
const Procedure = require('../models/procedure.model');
const StepProcedure = require('../models/step_procedure.model');
const TemplatePublic = require('../models/template_public_class');
const ReportTrip = require('../models/report_trip');
const WinterBreak = require('../models/winter_break.model');
const WinterBreakStudent = require('../models/winter_break_student.model');
const WinterBreakStudentAttendance = require('../models/winter_break_attendance.model');
const Post = require('../models/post.model');
const PostFile = require('../models/post_file.model');
const CommentPost = require('../models/comment_post.model');
const Question = require('../models/question.model');
const StudentPost = require('../models/student_post.model');
const StudentPostFile = require('../models/student_post_file.model');
const StudentAnswer = require('../models/student_answer.model');
const Assignment = require('../models/assignment.model');
const AssignmentClass = require('../models/assignment_class.model');
const PostDetail = require('../models/post_detail.model');
const Answer = require('../models/answer_question.model');
const StudentPostAttendance = require('../models/student_post_attendance.model');
const PostStudentList = require('../models/post_and_student.model');
const AssignmentCategory = require('../models/assignment_category.model');
const StudentAnswerOption = require('../models/student_answer_option.model');
const TestLink = require('../models/test_link.model');
const EventStudentAttendance = require('../models/event_student_attendance.model');
const NotificationStudent = require('../models/notification_student.model');
const LearningContentCategory = require('../models/learning_content_category.model');
const LearningContent = require('../models/learning_content.model');
const LearningContentClass = require('../models/learning_content_class.model');
const TemplateCategory = require('../models/template_category.model');
const TemplateContent = require('../models/template_content.model');
const StudentTemplate = require('../models/student_template.model');
const EventNoteParent = require('../models/event_note_parent.model');
const EventSubject = require('../models/event_subject.model');
const ContentDualPractice = require('../models/content_dual_practice.model');
const LessonOutline = require('../models/lesson_outline.model');
const StudentStatisticalMonth = require('../models/student_statistical_month.model');
const TeacherRegulations = require('../models/teacher_regulations.model');
const TeacherRegulationEValuate = require('../models/teacher_evaluate.model');
const ObservationSchedule = require('../models/observation_schedule.model');
const ClassStudentSticker = require('../models/class_student_sticker.model');
const IndividualLearningMonth = require('../models/individual_learning_month.model');
const IndividualLearningStudent = require('../models/individual_learning_student.model');
const IndividualLearningWeekly = require('../models/Individual_learning_weekly.mode');
const StudentTutoring = require('../models/student_tutoring.model');
const StudentTutoringDaily = require('../models/student_tutoring_daily.model');
const Promo = require('../models/promo.model');
const PromoVersion = require('../models/promo_history.model');
//Nếu muốn thay đổi bảng thì sử dung after hoặc force.
(async () => {
    try {
        await Account.sync();
        await File.sync();
        await Staff.sync();
        await Admin.sync();
        await Teacher.sync();
        await Student.sync();
        await FileProfile.sync();
        await Department.sync();
        await Recruitment.sync();
        await SourceApply.sync();
        await ApplicationLeave.sync();
        await Apply.sync();
        await SourceCollect.sync();
        await SourceSpend.sync();
        await Supplier.sync();
        await Course.sync();
        await CourseArise.sync();
        await PrintReceipt.sync();
        await Collect.sync();
        await Spend.sync();
        await CustomerSales.sync();
        await CustomerNote.sync();
        await LearningContentCategory.sync();
        await TemplateCategory.sync();
        await Classroom.sync();
        await CalendarDetail.sync();
        await ClassEvaluate.sync();
        await TeacherTime.sync();
        await StudentTest.sync();
        await AttendanceClassOnline.sync();
        await StudentList.sync();
        await StudentListHistory.sync();
        await TeacherList.sync();
        await Practice.sync();
        await PracticeStudent.sync();
        await PracticeAdults.sync();
        await PracticeTopicAdults.sync();
        await PracticeTopicDetailAdults.sync();
        await ProgressStudentClass.sync();
        await StudentEvaluate.sync();
        await StudentChangeHour.sync();
        await Template.sync();
        await Tuition.sync();
        await StudentAttendance.sync();
        await TestType.sync();
        await Test.sync();
        await Tutoring.sync();
        await CriteriaTest.sync();
        await Notification.sync();
        await Event.sync();
        await EventStudent.sync();
        await EventStudentAttendance.sync();
        await EventSummerClass.sync();
        await EventNoteParent.sync();
        await ClassTestCalendar.sync();
        await TemplateHistory.sync();
        await ContributeEvent.sync();
        await StudentOffSummer.sync();
        await Procedure.sync();
        await StepProcedure.sync();
        await TemplatePublic.sync();
        await ReportTrip.sync();
        await WinterBreak.sync();
        await WinterBreakStudent.sync();
        await WinterBreakStudentAttendance.sync();
        await TestLink.sync();
        await LearningContent.sync();
        await LearningContentClass.sync();
        await TemplateContent.sync();
        await StudentTemplate.sync();
        await EventSubject.sync();
        await ContentDualPractice.sync();
        await LessonOutline.sync();
        await StudentStatisticalMonth.sync();
        await TeacherRegulations.sync();
        await TeacherRegulationEValuate.sync();
        await ObservationSchedule.sync();
        await ClassStudentSticker.sync();
        await IndividualLearningMonth.sync();
        await IndividualLearningStudent.sync();
        await IndividualLearningWeekly.sync();
        await StudentTutoring.sync();
        await StudentTutoringDaily.sync();
        await Promo.sync();
        await PromoVersion.sync();
        // elearning
        await AssignmentCategory.sync();
        await Assignment.sync();
        await AssignmentClass.sync();
        await Post.sync();
        await PostStudentList.sync();
        await PostDetail.sync();
        await PostFile.sync();
        await CommentPost.sync();
        await Question.sync();
        await Answer.sync();
        await StudentPost.sync();
        await StudentPostFile.sync();
        await StudentAnswer.sync();
        await StudentAnswerOption.sync();
        await StudentPostAttendance.sync();
        await NotificationStudent.sync();
        console.log("Bảng đã được tạo thành công!");
    } catch (error) {
        logger.error(error);
        console.log('Không thể tạo được bảng');
    }
})();
